### ISSUE TITLE
Affinity Can't be set

### ISSUE THREAD

**Issue by parthbhatti** [Playhi/checkbox_list_tile_more_customizable#1]
we must import 
list_tile_more_customizable: ^1.2.2
library independently to solve

**Comment by Playhi** [comment]
b7d3711  
Directly export 'package:list_tile_more_customizable/list_tile_more_customizable.dart' for this problem in 1.0.2

**Comment by Playhi** [comment]
The problem seems to have been solved, so I will close this issue. Feel free to comment and it can be reopened.
